x = int(input("Enter the first number : "))
y = int(input("Enter the Second number : "))
print("Sum of",x,"and",y,"is : ",x+y)
print("Subtraction of",x,"and",y,"is : ",x-y)
print("Multiplication of",x,"and",y,"is : ",x*y)
print("Division of",x,"by",y,"is : ",x/y)
print("Floor value of",x,"by",y,"is : ",x//y)
print("Exponential of",x,"raised to",4,"is : ",x**4)